/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */S
package com.mycompany.avaliacao;

import java.awt.Color;
import java.util.Random;

/**
 *
 * @author Admin
 */
public class ProjetoIndividual extends javax.swing.JFrame {
        Integer numeromaxcpu = 0 ; 
        Integer numeromincpu =  100 ;
        Integer mediacpu = 0 ; 
        Integer contadorcpu = 0;
        Integer somacpu = 0;
        
        Integer numeromaxmemoria = 0; 
        Integer numerominmemoria = 4000 ;
        Integer mediamemoria = 0 ; 
        Integer contadormemoria = 0;
        Integer somamemoria = 0;
        
        Integer numeromaxdisco = 0 ; 
        Integer numeromindisco = 1000 ;
        Integer mediadisco = 0 ; 
        Integer contadordisco= 0;
        Integer somadisco = 0;
        
                
    /**
     * Creates new form ProjetoIndividual
     */
    public ProjetoIndividual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        barracpu = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        barradisco = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        barramemoria = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        mincpu = new javax.swing.JLabel();
        minmemoria = new javax.swing.JLabel();
        mindisco = new javax.swing.JLabel();
        medcpu = new javax.swing.JLabel();
        meddisco = new javax.swing.JLabel();
        medmemoria = new javax.swing.JLabel();
        maxcpu = new javax.swing.JLabel();
        maxdisco = new javax.swing.JLabel();
        maxmemoria = new javax.swing.JLabel();

        jLabel15.setText("max:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        barracpu.setForeground(new java.awt.Color(0, 0, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("CPU");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("DISCO");

        barradisco.setBackground(new java.awt.Color(0, 0, 204));
        barradisco.setForeground(new java.awt.Color(0, 0, 204));
        barradisco.setMaximum(4000);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("MEMÓRIA");

        barramemoria.setBackground(new java.awt.Color(51, 51, 255));
        barramemoria.setForeground(new java.awt.Color(0, 0, 153));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("GERAR DADOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mincpu.setText("min (0 a 10)");

        minmemoria.setText("min(0 a 10)");

        mindisco.setText("min(0 a 10)");

        medcpu.setText("med (11 a 80)");

        meddisco.setText("med (11 a 80)");

        medmemoria.setText("med(11 a 80)");

        maxcpu.setText("max (81 a 100)");

        maxdisco.setText("max (81 a 100)");

        maxmemoria.setText("max (81 a 100)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(barracpu, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(barradisco, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mindisco)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mincpu)
                                            .addComponent(minmemoria))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(107, 107, 107)
                                                .addComponent(jLabel1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(medcpu)
                                                            .addGap(80, 80, 80)
                                                            .addComponent(maxcpu)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(medmemoria)
                                                        .addGap(80, 80, 80)
                                                        .addComponent(maxmemoria))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(meddisco)
                                                            .addGap(80, 80, 80)
                                                            .addComponent(maxdisco)))))))
                                    .addComponent(barramemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(barracpu, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mincpu)
                    .addComponent(medcpu)
                    .addComponent(maxcpu))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(barradisco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mindisco)
                            .addComponent(meddisco)
                            .addComponent(maxdisco)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(barramemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minmemoria)
                    .addComponent(maxmemoria)
                    .addComponent(medmemoria))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Random cpu = new Random();
        Integer cpunumero = cpu.nextInt(101);
        contadorcpu ++ ;
        somacpu = somacpu + cpunumero ;
        mediacpu = somacpu / contadorcpu ;
        
        medcpu.setText(String.format("%d" ,cpunumero));
        mincpu.setText((numeromincpu) + "%");
        maxcpu.setText((numeromaxcpu)+ "%") ;
        
        barracpu.setValue(cpunumero);
        barracpu.setStringPainted(true);
        
        mincpu.setForeground(Color.black);
        medcpu.setForeground(Color.blue);
        maxcpu.setForeground(Color.red);
        
        if(cpunumero > numeromaxcpu){
            numeromaxcpu = cpunumero ;
        }
            if(cpunumero < numeromincpu){
            numeromincpu = cpunumero ;
        } 
        maxcpu.setText(String.format("%d%%",numeromaxcpu )) ;
        mincpu.setText(String.format("%d%%",numeromincpu )) ;
        medcpu.setText(String.format("%d%%",mediacpu )) ;
        
        
        
        Random disco = new Random();
        Integer disconumero = disco.nextInt(4001); 
        contadordisco ++ ;
        somadisco = somadisco + disconumero ;
        mediadisco = somadisco / contadordisco ;
        
        meddisco.setText(String.format("%d%%" ,disconumero));
        mindisco.setText("0");
        maxdisco.setText(("4000")+ "GB");
        
        barradisco.setValue(disconumero);
        barradisco.setStringPainted(true);
        
        
        
        mindisco.setForeground(Color.black);
        meddisco.setForeground(Color.blue);
        maxdisco.setForeground(Color.red);
        
        if(disconumero > numeromaxdisco){
            numeromaxdisco = disconumero ;
        }
        if(disconumero < numeromindisco){
            numeromindisco = disconumero ;
        }
        maxdisco.setText(String.format("%d GB",numeromaxdisco )) ;
        mindisco.setText(String.format("%d GB",numeromindisco )) ;
        meddisco.setText(String.format("%d GB",mediadisco )) ;
        
        
        
        Random memoria = new Random();
        Integer memorianumero = memoria.nextInt(101); 
        contadormemoria ++ ;
        somamemoria = somamemoria + memorianumero ;
        mediamemoria = somamemoria / contadormemoria ;
        
        medmemoria.setText(String.format("%d" ,memorianumero));
        minmemoria.setText("0");
        maxmemoria.setText(("400")+ "GB");
        
        barramemoria.setValue(memorianumero);
        barramemoria.setStringPainted(true);
        
        minmemoria.setForeground(Color.black);
        medmemoria.setForeground(Color.blue);
        maxmemoria.setForeground(Color.red);
        
       if(memorianumero > numeromaxmemoria){
            numeromaxmemoria = memorianumero ;
        }
        if(memorianumero < numerominmemoria){
            numerominmemoria = memorianumero ;
        }
        maxmemoria.setText(String.format("%d GB",numeromaxmemoria )) ;
        minmemoria.setText(String.format("%d GB",numerominmemoria )) ;
        medmemoria.setText(String.format("%d GB",mediamemoria )) ;
        
        

    

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoIndividual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barracpu;
    private javax.swing.JProgressBar barradisco;
    private javax.swing.JProgressBar barramemoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel maxcpu;
    private javax.swing.JLabel maxdisco;
    private javax.swing.JLabel maxmemoria;
    private javax.swing.JLabel medcpu;
    private javax.swing.JLabel meddisco;
    private javax.swing.JLabel medmemoria;
    private javax.swing.JLabel mincpu;
    private javax.swing.JLabel mindisco;
    private javax.swing.JLabel minmemoria;
    // End of variables declaration//GEN-END:variables
}
